[project]
name = "openai-quickstart"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.0.15",
    "docarray>=0.41.0",
    "faiss-cpu>=1.11.0",
    "google-search-results>=2.4.2",
    "gradio>=5.36.2",
    "huggingface>=0.0.1",
    "ipython>=9.4.0",
    "langchain[google-genai]>=0.3.26",
    "langchain-chroma>=0.2.4",
    "langchain-community>=0.3.27",
    "langchain-core>=0.3.68",
    "langchain-experimental>=0.3.4",
    "langchain-huggingface>=0.3.0",
    "langchain-openai>=0.3.27",
    "langchain-text-splitters>=0.3.8",
    "langsmith>=0.4.4",
    "matplotlib>=3.10.3",
    "notebook>=7.4.4",
    "numpy>=2.3.1",
    "openai>=1.93.3",
    "pandas>=2.3.1",
    "plotly>=6.2.0",
    "rank-bm25>=0.2.2",
    "scikit-learn>=1.7.0",
    "sentence-transformers>=5.0.0",
    "termcolor>=3.1.0",
    "tiktoken>=0.9.0",
    "unstructured>=0.18.3",
    "python-dotenv>=1.1.1",
    "langgraph>=0.5.2",
    "tavily-python>=0.7.9",
    "langchain-tavily>=0.2.7",
    "pandas-stubs==2.3.0.250703",
]

[[tool.uv.index]]
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
default = true
